### ISSUE TITLE
Change ember data URLs back to `release`

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1036]
Previously, we hard-coded API docs urls to v3.10. Now that Ember Data docs have stabilized, we should change them back to `release` and update the URL if needed. It is ok to submit a PR for one  page at a time, or all of them at once.

example from [this page](https://github.com/ember-learn/guides-source/blob/master/guides/release/models/creating-updating-and-deleting-records.md)

```
[`createRecord()`](https://api.emberjs.com/ember-data/3.10/classes/DS.Store/methods/createRecord?anchor=createRecord)
```

should become 

```
[`createRecord()`](https://api.emberjs.com/ember-data/release/classes/Store/methods/createRecord?anchor=createRecord)
```

To-do:
- change ember data API urls to `release`, for only the files in `guides/release` of this repository
- Check to make sure your new URLs work. Many will need to be updated. You can try using https://github.com/ember-learn/guides-source/pull/966 if you are careful not to DDOS the docs site

Note that if you submit a PR and the preview build fails yet Travis tests pass, there's an issue with deploy timeouts and it's probably not your PR causing a problem. A maintainer will take a look and resolve it.

**Comment by maxwondercorn** [comment]
I'll pick this one up.  Probably won't be able to start on it until early next week

**Comment by maxwondercorn** [comment]
@jenweber I started changing the links to 'release' and noticed that there are many references to and examples containing `DS.attr`, `DS.model`, `DS.belongsTo`, etc. 

Since the ember-data change to module imports these don't match current usage and the api examples we are linking to.  Should I work on cleaning these up too?

I recall an issue/PR to change them when the import modules were released. I thought the PR was against guides-source but maybe not?
