### ISSUE TITLE
"First" page in every group takes a few seconds before loading when clicked

### ISSUE THREAD

**Issue by jacobq** [ember-learn/guides-source#1266]
Steps to reproduce:

1. Navigate to https://guides.emberjs.com/release/
2. Click on a group to expand it, e.g. "CORE CONCEPTS" > "Components"
3. Optional: open dev tools to monitor network activity
4. Click the first link, e.g. "Templates are HTML"
5. Wait for page to load -- takes longer than expected, apparently due to 404 waiting for https://guides.emberjs.com/content/v3.15.0/components.json

Note 1: other pages (not the first link in their respective group) do not exhibit this behavior
Note 2: loading the problematic pages directly by their URL seems to avoid the problem (request still happens but doesn't delay page rendering)
Note 3: tested on 1/10/2020 in Chrome 79 on Linux x64, but I doubt that matters as it seems to be either an application or hosting problem.

**Comment by jacobq** [comment]
Also, Ember Inspector's "Promises" tracking tool shows a rejection "DS: RESTAdapter#ajax GET to /content/v3.15.0/components.json"

**Comment by diamondo25** [comment]
Experienced this issue too. Not a good experience if you want to start using Ember, as it looks like the page link doesnt work.

**Comment by marcelotedeschi** [comment]
I experienced this issue as well and took a deeper look into what is (potentially) happening.

Essentially, from what I understand, this is an upstream "issue" (though apparently the intended design), from [guidemaker](https://github.com/empress/guidemaker).

More specifically, it happens [here](https://github.com/empress/guidemaker/blob/master/app/routes/version/show.js#L49). When the user navigates to a `version.show.index` ("first page" of sections) route, there is a forced transition to the parent route, that is, replacing the `index` path. Consequently ([L60](https://github.com/empress/guidemaker/blob/master/app/routes/version/show.js#L60)), the record query cannot find the file because the required file is _actually_ called `index.js` and not the parent route `getting-started.json`


![Screen Shot 2020-02-14 at 11 50 32 AM](https://user-images.githubusercontent.com/5921389/74524911-3a119500-4f20-11ea-914c-37f36ce46f8b.png)

Nevertheless, that is the "intended design", since there's a [catch block (L72)](https://github.com/empress/guidemaker/blob/master/app/routes/version/show.js#L64-L72) which then queries for the correct `${path}/index` file. From what I can gather, the only useful outcome of this design is not to have the `/index` on the page URL (but I'm probably not seeing a bigger picture here).

Maybe @mansona could give a quick explanation on the intention?

---

From the context of this repo, I don't really get why the 404 response is taking that long (see network waterfall on the picture above). On development, this fail/retry is quite fast, so although it's a strange design, it does work 🤷‍♂. 

Finally, I'd be happy to help with improving this if needed :)
