### ISSUE TITLE
Move Build Targets content to CLI guides

### ISSUE THREAD

**Issue by mehulkar** [ember-learn/guides-source#1377]
Corollary to https://github.com/ember-learn/cli-guides/issues/159

**Comment by jenweber** [comment]
The learning team & friends discussed this and we want to move forward.

The Build Targets page in the Guides should:
- have most content removed, and replaced with a link to the CLI Guides
- It should retain at least one paragraph explaining why and when someone would need this info
- It may include links to other helpful resources

The goal is that the page that remains should have at least a little rich content and not just look like a placeholder. Otherwise, the Guides will seem like a "pruned tree" when instead it should read like a book.

The CLI Guides PR should be merged first so we have something to link to.
