### ISSUE TITLE
Remove triple curly usage

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#1421]
https://guides.emberjs.com/release/components/looping-through-lists/ currently includes usage of triple curlies `{{{`, which is not recommended and is linted against.

We need to analyse the prose and code to see how to remove the usage, since the specific guide is focused on looping lists.

If you're looking to pick this issue up and need more context please ask here or on Discord!

**Comment by fozy81** [comment]
@locks  I was hoping to pick this one up. My plan was to create an ember app with the example as it is currently explained/coded in the guidance. Once I've got that minimal app running, I'll look at how the code can be change to remove the `{{{` and document the changes in code and guidance as required. Does that sound a good approach?

**Comment by fozy81** [comment]
@ijlee2 One alternative is to remove html from the example messages. But perhaps that is skirting around the issue?  

So agree, perhaps updating with words of the affect that {{{}}} is okay for mock data/development but is could be linted against in your text editor but use htmlSafe for any user entered text.

**Comment by ijlee2** [comment]
@fozy81 Let's try updating the prose in Zoey Says. I'll let you come up with a change, then I can come up with a suggestion for improvement in your pull request.

- I'm ok with mentioning triple curlies is safe for mock data and non-production apps
- Do mention htmlSafe and link it to the API docs

To my understanding, `htmlSafe` does not mean the HTML code has been sanitized. The developer still needs to sanitize code to prevent security issues. I think this is something I'd like to see  clarified in Zoey Says, instead of the current sentences "Additionally... before inserting it."

**Comment by fozy81** [comment]
@ijlee2 Please see PR, let me know your thoughts - it's so hard to get the right tone/words. Do you think an 'in-depth' topic should cover sanitizing input and using htmlSafe in more detail?
