### ISSUE TITLE
Fix API links in the Guides that go to "release"

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1440]
When we released Octane, the API docs changed a whole bunch! Ideal Guides UX is that if someone is on an older version of Ember, like 3.12, if they follow the links to the API docs, they should see 3.12 docs (non-Octane). However, right now, a lot of links point directly to `api.emberjs.com/ember/release` and `api.emberjs.com/ember-data/release`.

To close this ticket, do a find-replace to change the "release" links to point to the appropriate version, for each version of the guides. The lastest version of the guides should still point to `release`, so don't change those.

**Comment by ijlee2** [comment]
@jenweber @MelSumner Before asking for community help, I think we may need a concrete plan for how we'll update all links to the API Guides across all versions. To my understanding:

Currently, when there's a new Ember release, we copy-paste the `release` folder so that there will be a new folder for what used to be the release version. Take the upcoming 3.20 release as example. We'd copy-paste the `release` folder to create `3.19` folder.

Somehow, we'd need to find and replace all instances of "release" in the `3.19` folder to "3.19," and check that these links are all correct. Do we have a mechanism to automate this process?

As an alternative solution, would it be possible to send metadata to API Guides, so that the Ember Guides can always use `/release` in the links and the API Guides is responsible for redirecting from `/release` to the correct version?

**Comment by jenweber** [comment]
Good questions! We don't have a mechanism to automate it, besides a careful find-replace. If you search the docs for `/release/` it will bring up all the places to change. We have a link checker that can be run on-demand: https://github.com/ember-learn/guides-source#internal-and-external-links If someone wants to take this on, I suggest fixing links for just one version of the guides and PR-ing that, as a warmup.

I would not want to make any changes to the API docs app, since its redirect rules are pretty complicated and the app is brittle.

There may be a way to build this into Guidemaker, but it's likely much faster to do a find-replace than code a new feature.

**Comment by ijlee2** [comment]
@jenweber Sounds good. Thanks for the explanation! I can try find-and-replace on `3.18` and see how it goes.

**Comment by ijlee2** [comment]
At the Learning Team meeting on July 30, we discussed updating the API links in the Ember Guides in all versions if possible. I made checklists below to divide work and track progress.

To ensure that search results in Google point to the `release` in API Guides, we'll want to look at the problem of addressing canonical links in the [API repo](https://github.com/ember-learn/ember-api-docs) soon.

## Phase 1
- [ ] `v3.19`
- [x] `v3.18`
- [ ] `v3.17`
- [ ] `v3.16`
- [ ] `v3.15`

## Phase 2
- [ ] `v3.14`
- [ ] `v3.13`
- [ ] `v3.12`
- [ ] `v3.11`
- [ ] `v3.10`
- [ ] `v3.9`
- [ ] `v3.8`

## Phase 3
- [ ] `v3.7`
- [ ] `v3.6`
- [ ] `v3.5`
- [ ] `v3.4`
- [ ] `v3.3`
- [ ] `v3.2`
- [ ] `v3.1`
- [ ] `v3.0`

## Phase 4
- [ ] `v2.18`
- [ ] `v2.17`
- [ ] `v2.16`
- [ ] `v2.15`
- [ ] `v2.14`
- [ ] `v2.13`

## Phase 5
- [ ] `v2.12`
- [ ] `v2.11`
- [ ] `v2.10`
- [ ] `v2.9`
- [ ] `v2.8`
- [ ] `v2.7`

## Phase 6
- [ ] `v2.6`
- [ ] `v2.5`
- [ ] `v2.4`
- [ ] `v2.3`
- [ ] `v2.2`
- [ ] `v2.1`
- [ ] `v2.0`

## Phase 7
- [ ] `v1.13`
- [ ] `v1.12`
- [ ] `v1.11`
- [ ] `v1.10`

**Comment by ijlee2** [comment]
To all: If you can help, please let us know! 🙂

**Comment by neojp** [comment]
@jenweber & @ijlee2, I went ahead and wrote a script that will allow us to do this process more quickly. This also hooks into the current process to create new releases and automates the process for us for future releases. You can see it in PR #1592.

![image](https://user-images.githubusercontent.com/127994/97798177-b86ab000-1bf1-11eb-9fd0-20bbff8b875b.png)

**Comment by neojp** [comment]
I have ran the script through all versions and submitted PRs for the ones that had any link edits, once these are approved and merged we should be able to close this issue.

**Comment by ijlee2** [comment]
I believe this issue can be considered done now. 🥳
