### ISSUE TITLE
I've got a bug while following the ember guides.

### ISSUE THREAD

**Issue by chiaraani** [ember-learn/guides-source#1521]
I've learning from the tutorial. But in this [chapter](https://guides.emberjs.com/release/tutorial/part-2/ember-data/ ), I got this error when running my tests:  
```
2. Unit | Serializer | application: it serializes record
No model was found for 'application' and no schema handles the type
```
This is my [ember app](https://github.com/chiaraani/super-rentals-exercise)

**Comment by ijlee2** [comment]
Hi, @chiaraani. Thanks for trying out the Ember official tutorial and providing feedback! 🎉


## 1. What may have happened

It looked like you may have used the Ember CLI to create the `application` serializer? In the terminal, you might have typed,

```bash
ember generate serializer application

# or,
ember g serializer application
```

In https://guides.emberjs.com/release/tutorial/part-2/ember-data/, I noticed that the screenshot for tests is missing the test for `application` serializer. (If the test existed, it would probably appear as test `#24`.)

<img src="https://guides.emberjs.com/images/tutorial/part-2/ember-data/pass-2@2x.png" width="640">

In other words, I think the tutorial may have assumed that you didn't create the `application` serializer by using Ember CLI, but by manually creating a file and copy-pasting the code into the file.


## 2. What can you do to solve the failing test

By default, Ember CLI creates a test file when you generate something. For example, the command above will create the test file `super-rentals-exercise/tests/unit/serializers/application-test.js`.

The tests in a test file are always **placeholders**. Ember expects you to update tests so that they are meaningful and accurately model what your end user (customer) might do in your app.

### Option a. Delete the test file

It has been a while since I read the tutorial.

I don't think the tutorial will later cover writing unit tests for the `application` serializer. Writing unit tests for a serializer isn't something that I would expect a new Ember developer to learn and practice immediately.

Feel free to delete the test file, then run `ember test` again to check that all tests now pass.


### Option b. Update the test file

In case you do want to fix the failing test, let's have a look at the test file for `application` serializer:

```javascript
import { module, test } from 'qunit';
import { setupTest } from 'ember-qunit';

module('Unit | Serializer | application', function(hooks) {
  setupTest(hooks);

  // Replace this with your real tests.
  test('it exists', function(assert) {
    let store = this.owner.lookup('service:store');
    let serializer = store.serializerFor('application');

    assert.ok(serializer);
  });

  test('it serializes records', function(assert) {
    let store = this.owner.lookup('service:store');
    let record = store.createRecord('application', {});

    let serializedRecord = record.serialize();

    assert.ok(serializedRecord);
  });
});
```

This file can be hard to read and understand for new Ember developers 😓. We see that there are 2 tests that Ember CLI created for us.

Each test tells a story. The 1st one says, `try to find the serializer for the application model`, while the 2nd says, `try to serialize the application model`. (Right now, we might not understand what "serialize" means. That's okay. We can assume that it's some action that we want to perform on the model.)

From the story above, you might see why the test failed. We don't have a model named `application` yet, only a model named `rental`.

So the solution is to replace the word `application` with `rental`, a model that does exist in your app.

```javascript
import { module, test } from 'qunit';
import { setupTest } from 'ember-qunit';

module('Unit | Serializer | application', function(hooks) {
  setupTest(hooks);

  // Replace this with your real tests.
  test('it exists', function(assert) {
    let store = this.owner.lookup('service:store');
    let serializer = store.serializerFor('rental');

    assert.ok(serializer);
  });

  test('it serializes records', function(assert) {
    let store = this.owner.lookup('service:store');
    let record = store.createRecord('rental', {});

    let serializedRecord = record.serialize();

    assert.ok(serializedRecord);
  });
});
```

The solution we took here is somewhat an anomaly. The `application` serializer (the `application` adapter, too) is special because it allows you to define "rules" that apply to your app _in general_.

When you create a serializer for an actual model, you will see that the unit tests that Ember CLI creates will automatically pass.

**Comment by chiaraani** [comment]
Thanks so much  @ijlee2 ! I had the same problem with another ember app I was making on my own, as I am not a new developer, I've easily fixed it. But then I decided to read the tutorial first, I was such tired though, that I did not read the tutorial well or remember how to fix the placeholder test. It actually was so easy. I'm sorry for minding you.

**Comment by ijlee2** [comment]
No worries. I appreciate your asking help and engaging with the Ember community!
