### ISSUE TITLE
this.render in Route not well documented

### ISSUE THREAD

**Issue by Benjy1979** [ember-learn/guides-source#1633]
The ability to call this.render() in renderTemplate has not been well documented. Some questions on reading it immediately spring to mind, and some after experimentation:

[https://api.emberjs.com/ember/3.24/classes/Route/methods/render?anchor=render](https://api.emberjs.com/ember/3.24/classes/Route/methods/render?anchor=render)

1. What about query params and route arguments required for that route that you are rendering into another template?
2. Does it call the model() hook of the owner of renderTemplate function or the route you are rendering, by default, if any? It does mention you can pass a model and does mention that the model of "the controller" is used, but no details on which controller it is referring to (ie the controller owner of renderTemplate or the controller of the route you are rendering) nor how that model is obtained ie does it call the route's model() or is it relying on a previous initialisation of that model in the controller.

**Comment by locks** [comment]
Hi @Benjy1979, thanks for reporting! These APIs have in general not been recommended for a while and as of 3.26 they are officially deprecated https://deprecations.emberjs.com/v3.x#toc_route-render-template. Part of the reason is that they raise questions similar to yours and we have better solutions now.
I hope the migration guides are helpful in adjusting your code to not rely on `render`/`renderTemplate`. I'm closing the issue because of the deprecation.

Regarding your questions,

2. I'll answer this one first because it helps with the other question.

> Does it call the model() hook of the owner of renderTemplate function or the route you are rendering, by default, if any?

The owner of the `renderTemplate` as the hook methods are defined in that class.

> It does mention you can pass a model and does mention that the model of "the controller" is used

It's been a while, but I'm pretty sure that the `model` and the `controller` that `renderTemplate` receives are the results of the `model()` and `setupController()` hooks in the owner of the `renderTemplate`. If you define `controllerName` somewhere, that controller will be used instead.

1.
> What about query params and route arguments required for that route that you are rendering into another template?

I'm not sure what you mean here? Query params are bound to the controller, so if you're using a template that directly uses query params, you might have to use the controller that pair with that template.

Let us know if you have more questions.

**Comment by Benjy1979** [comment]
__It's been a while, but I'm pretty sure that the model and the controller that renderTemplate receives are the results of the model() and setupController() hooks in the owner of the renderTemplate. If you define controllerName somewhere, that controller will be used instead.__ 

The question I was asking refers to the route that this.render is rendering rather than the owner of renderTemplate that has the.render() in it. 

But I think I'll take your answer as a bottom line: Do not use renderTemplate! So thanks for your reply.
