### ISSUE TITLE
page-title doesn't work in Quickstart

### ISSUE THREAD

**Issue by pradeepcep** [ember-learn/guides-source#1740]
I am following through https://guides.emberjs.com/release/getting-started/quick-start/, and the code snippet there (for the generated `scientists` route) uses the `page-title` tag in the template (in `app/templates/scientists.hbs`).

It didn't work for me, and the route was not rendered even though I had `{{outlet}}` in my `applicaiton.hbs`. It looks like I need the `ember-page-title` add-on for this to work? Doing `ember install ember-page-title` solved it for me, but it would be great if this info is included in the guide.

Alternatively, the `page-title` could be removed from the suggested code snippet on the page.

P.S: I'm just getting started, so I could be totally wrong about this.

**Comment by locks** [comment]
What version of ember-cli did you use to generate the application? Can you also check `ember-source` in the `package.json` file and tell us what version it is?
`ember-page-title` has been included by default when generating applications some versions ago, so the Quick Start should be correct.

**Comment by pradeepcep** [comment]
```
$ ember --version
ember-cli: 3.13.2
node: 12.18.3
os: darwin x64
```

**Comment by pradeepcep** [comment]
I see from the `ember-cli` repo that there have been some releases after `3.13.2`, but even when I did the `npm install -g ember-cli` and `npm update ember-cli` suggested in various places, I still end up with `3.13.2`.

I guess this is something platform-specific? I tried updating to the latest LTS version of `node` and upgraded `npm` too, but still got `3.13.2`.

This is no longer a problem for me, because I installed the add-on — and if using the latest version resolves this, then I doubt anyone else is likely to encounter this. But I'm happy to provide any additional info if that would help.

**Comment by ijlee2** [comment]
@pradeepcep Hello, thanks for opening an issue and describing the problem that you had encountered while following the Quick Start.


### Part 1

Once you have `ember-cli` globally installed, you can run the following command to check which version of Ember will be installed when you run the command `ember new <application-name>`:

```sh
ember --version

# Sample output
ember-cli: 3.27.0
node: 14.15.4
os: darwin x64
```

So, had I run `ember new hello-world`, I would be creating an Ember 3.27 app (rather than the latest, which is 3.28 at the moment). To ensure that `ember new` installs an app with the latest Ember, I'd need to update `ember-cli` globally, by running the command `npm install -g ember-cli`.

I recommend that you keep `ember-cli` up-to-date so that you can work with the latest features of Ember at any time. `ember-cli` will respect the Ember version for any existing app.


### Part 2

I found that the blueprint for `package.json` did not include `ember-page-title` until Ember 3.24.0.

- [Ember 3.23.0](https://github.com/ember-cli/ember-cli/blob/v3.23.0/blueprints/app/files/package.json#L44-L45)
- [Ember 3.24.0](https://github.com/ember-cli/ember-cli/blob/v3.24.0/blueprints/app/files/package.json#L49)

As a result, I think it's a valid problem that the Quick Start mentions `{{page-title}}` helper without context. I don't think we should assume that a new developer will know that the `release` version of the Guides means that the content may be only applicable to the latest version of Ember.

I'll try to make time this week to update the Quick Start for versions 3.25 to release (3.28).
