### ISSUE TITLE
Action helper uses `sendAction` example

### ISSUE THREAD

**Issue by theroncross** [ember-learn/guides-source#219]
The `Invoking an Action` section uses [the now deprecated](https://emberjs.com/api/ember/release/classes/Ember.Templates.helpers/methods/yield?anchor=action) `sendAction` as an example.

If anyone can think of another clear use of currying, I'd be happy to open a PR.

**Comment by Gaurav0** [comment]
I don't think you need a different use case. You can use the same example; just change the invocation to that of a closure action.

Instead of calling `this.sendAction('submit', 'bob')` just replace it with `this.get('submit')('bob')` or even `this.submit('bob')`, that's how you call a closure action.

**Comment by theroncross** [comment]
Sorry - wrong repo. Closing in favor or ember-learn/ember-api-docs#564
