### ISSUE TITLE
Some of the language in the Contributing guide is a bit fuzzy

### ISSUE THREAD

**Issue by zachgarwood** [ember-learn/guides-source#235]
Reading through the Contributing guide as a potential new contributor, these bits gave me pause:

> Fixing problems: If you find a problem on a particular page in the Guides, the most helpful thing you can do is open a pull request. If you're not sure how to fix it, open an issue.

This seems straight-forward on its own, but is then immediately contradicted by the next two bullet points. This bullet point implies that new contributors can open PRs at their discretion, but the following two indicate that they must first have significant interaction with the maintainers first before proposing changes. I think we should get rid of this bullet point altogether. 

> The best way to get started contributing content is to pick up one of these issues.

It is not clear what is meant by "pick up one of these issues." Non-maintainers are unable to assign themselves to an issue, so it is unclear how a new contributor is supposed to indicate that they have "picked up" an issue.

> Add a comment to let the maintainers know that you're interested...

Is leaving a comment a discrete step in the contribution process or simply a courtesy to the maintainers? Asked another way: Should the new contributor wait for permission from the maintainers to begin working on the issue, or once they've commented, can they begin work on their PR?

Overall, the main thrust of this issue is that this contributing guide should explain the *exact steps* a new contributor should follow in order to be able to contribute, even spelling out the steps that may seem obvious the the existing maintainers.

**Comment by mansona** [comment]
Hey @zachgarwood 👋 

Thanks for bringing this up! It's always good to discuss things that can be improved, especially when there is a potential that it might be preventing people from feeling like they can contribute. 

I'll go through a few of my thoughts on the issue here but I don't see myself "answering" your questions, more so giving you a bit of context on what we were going for in the Contributing guide. If the context helps us make it better then great 🎉

Firstly there is a bit of an implicit difference between two types of contributions that may need to be made more clear in the contributing guide 🤔 When it says "If you find a problem" that is essentially talking about a bug, typo or something that is plainly wrong and should be updated. You will see quite a few small PRs that were merged recently (thanks to Hacktoberfest 😂) that would fall into that category. You can take a look [here](https://github.com/ember-learn/guides-source/pulls?q=is%3Apr+is%3Aclosed) and you may notice that a lot of the contributors there are first-time contributors too 🎉 

What the rest of the contributing guide is trying to communicate is not a **restriction** or **gatekeeping** way of preventing new contributors from making any larger contributions, but instead a way to hopefully communicate that if someone is due to make any signficant changes that they check-in to see if it is in line with the direction of the project. The last thing we want is for someone to go through the substantial effort to completely re-work every part of the Guides to use something like the Class style of defining components (just as an example) and for that PR to essentially be unmergable and hard to rebase when it comes to the time that it can be merged 😞In an example like this, if asked we might say "we can't quite start that yet but here is another thing that we would like some help on" and point them towards an issue that we know we want help with (for example [this one](https://github.com/ember-learn/guides-source/issues/164)). I hope that helps explain what is potentially a bit too implicit in the contributing guides 🤔 essentially we are **never** trying to restrict who is contributing, we are just trying to help any new contributors be as effective as possible and maximise the chance that their PR is mergable 👍 

As for "claiming an issue" we can definitely be more explicit here. Having a non-contributor comment on something and saying "I'll take this" is what we want people to be doing, so that we don't have cases where 2 people attempt an issue and we can only merge one of them. Again it's to help maximise that PRs are mergable and that there is no "wasted effort".

**Comment by zachgarwood** [comment]
I'm less concerned that the guide is restrictive or gatekeeping, and more concerned that it doesn't adequately explain the contribution process.

**Comment by MelSumner** [comment]
@zachgarwood one of the @ember-learn/learning-team goals before EOY is to have a clear contributing guide. We agree that it's not super easy to understand and we are working on it. Thank you for your feedback, it's helpful!
