### ISSUE TITLE
Analyze Section: Templates

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#252]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Section to review: 
[Templates](https://guides.emberjs.com/release/templates/handlebars-basics/)

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by cah-danmonroe** [comment]
Just a reminder that I have already submitted a PR #292 where I have already converted the 3.6 documentation to angle brackets. I can address further  #issues from there.

**Comment by locks** [comment]
Update for Octane layout file paths.
Update for native classes.
Update `LinkComponent`.

## Links

Cover [`Router helpers`](https://github.com/emberjs/rfcs/pull/391).

**Comment by pzuraq** [comment]
- [ ] Introduction ([PR](https://github.com/ember-learn/guides-source/pull/477))
  - Generally needs to be more like Jen's PR 😛 
- [ ] Templating Basics
  - "Binding Element Attributes" feels like it should belong here
  - Could be merged into the introduction, or parts of the introduction could be split out into a separate section that focusses just on the templating syntax.
  - Should cover:
    - Template bindings/interpolation
    - Attribute bindings
    - Interpolation _within_ attribute values (e.g. `class="foo {{dynamicClass}}"`)
- [ ] Helpers
  - "Built-in Helpers", "Conditionals", "Displaying a List of Items", and "Displaying the Keys in an Object", and "Writing Helpers" could all be handled better by a single unified helpers section
  - Show be about how to do programming logic in templates
  - Should emphasize that it's _not_ JS in templates, but it _does_ allow you to do as much or as little as you want. Definitely should mention the "logicless-templates" pattern, and compare to "template-heavy" patterns (both are options)
  - Comparisons to Lisp/Clojure?
  - Functional Programming!!!
  - Should cover
    - Built in helpers: `each`, `each-in`, `if`, `get`, `let`
    - Writing and using your own helpers
- [ ] Actions
  - Should be updated to use `onclick=` style actions
  - Should be updated to use the `@action` decorator instead of the `{{action}}` helper
  - This still belongs in templating in general, since bound actions need to be assigned to an `onclick` handler or a modifier to work correctly.
- [ ] Links
  - Update to refer to the `link-to` component as a helper, I think this will be less confusing than explaining that some components _must_ be invoked using curly syntax.
- [ ] Input Helpers
  - Update to refer to these as components, since they can (and generally should) be invoked with angle bracket syntax now.
  - Update to angle bracket syntax.
- [x] Development Helpers - stays the same

**Comment by MelSumner** [comment]
Updated the guide template issue to reflect this analysis. Thank you!! 👍
