### ISSUE TITLE
Analyze Section: Application Concerns - Dependency Injection

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#272]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
Applications: Dependency Injection

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by locks** [comment]
Update for Octane layout.
Update for native classes.

@ef4 can you do a conceptual review of this guide?

**Comment by ef4** [comment]
I have reviewed the DI page. It needs some love.

I would like to propose significantly re-ordering the whole thing, because today it's in almost exactly the wrong order (from most abstract & advanced to most concrete & important to beginners).

The new sections would be:
 - "Injecting Dependencies": this would be a rework of the current "Factory Injections" section. It should lead with what is currently labeled "Ad-Hoc" injections. That label is bad because it makes it sounds like they're wrong, when really they are the best way to do it. It can then move on to type injections and instance injections, but making it clear that those are _advanced_ techniques typically used within addon libraries.
 - "Looking Up Dependencies": this is the current "Factory Instance Lookups" section. There's no reason to hammer people with jargon like "factory instance", just stick to "dependency" throughout this page, the page is about _dependency_ injection.
 - "Registering Dependencies": this would be a rework of the current "Factory Registrations" section. It should only presume knowledge of Initializers (which it can hyperlink to), and it should show all the examples _in the context of_ initializers. It does _not_ need to introduce the words "registry" or "owner" or "Application" or "ApplicationInstance". It can introduce the word "factory" to explain the difference between the default behavior and `instantiate: false`.
 - "Understanding the Ember DI Architecture": this is where we'd put the highly abstract stuff defining "registry" and "owner". Even here I would drop attempts to define Application and ApplicationInstance. It's not central to the text, and you can hyperlink to their own API docs. 

All of what I just described is improvements to the presentation, not changes to the content. The content changes we need for Octane and native classes are:

 - all uses of `extend` should become native class extend instead
 - this implies teaching `inject` as a decorator
 - the examples that use `@ember/component` would change to use `@glimmer/component`

**Comment by MelSumner** [comment]
https://github.com/ember-learn/guides-source/issues/449 

Thanks @ef4 !
