### ISSUE TITLE
Routes should automatically load first sub-section

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#294]
## Issue Description
All URLs should automatically load the first sub-section if there is no main section content, or content should be included for that URL. This falls within our self-imposed & sensible constraint of "don't break the web". 

As an example, [https://guides.emberjs.com/release/getting-started/](https://guides.emberjs.com/release/getting-started/) automatically loads one of the sub-sections. 

However, https://guides.emberjs.com/release/glossary/ returns this: 
![image](https://user-images.githubusercontent.com/4587451/49227543-efedd380-f3ae-11e8-8b5e-5b352144d212.png)

## To Fix
Update each section to at least re-direct to first sub-section if no primary section content exists. 

### List of routes to be updated
- [ ] https://guides.emberjs.com/release/tutorial/ 
- [ ] https://guides.emberjs.com/release/templates/
- [ ] https://guides.emberjs.com/release/components/
- [ ] https://guides.emberjs.com/release/applications/
- [ ] https://guides.emberjs.com/release/addons-and-dependencies/
- [ ] https://guides.emberjs.com/release/configuring-ember/
- [ ] https://guides.emberjs.com/release/contributing/
- [ ] https://guides.emberjs.com/release/glossary/

**Comment by mansona** [comment]
This issue is related to this PR: https://github.com/ember-learn/guides-source/pull/140

The main bit of code that is needed is that we need to add a test to the [markdown tests](https://github.com/ember-learn/guides-source/tree/master/test) that errors when a guides **folder** is missing an index.md file.

The above PR was blocked on this PR https://github.com/ember-learn/guides-app/pull/213 which allowed us to define a **redirect** for the pages that would be moved to form the index.

I hope all this makes sense 👍

**Comment by mansona** [comment]
I am taking a look at this now 👍

**Comment by locks** [comment]
Clicking the mentioned links redirects properly!
