### ISSUE TITLE
Re-order the table of contents

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#393]
Following the direction outlined in [RFC 431](https://github.com/jenweber/rfcs/blob/guides-restructure/text/0431-guides-restructure.md), re-order the table of contents for the guides. 

Because of the Guides app architecture, we can move content around while preserving existing links. The Table of Contents specified in the pages.yml file of guides-source can have any paths, and is not 100% dependent on the physical file structure to create URLs. 

Order: 
- **What is Ember?**
- Getting Started
- ~Tutorial~
- ~The Object Model~
- Templates
- Components
- ~Controllers~
- Routing
- **State management**
- **Services**
- Ember Data (renamed from "Models")
- Addons and dependencies
- Testing
- Configuration (renamed from "Configuring Ember.js")
- Application Concerns
- Ember Inspector
- ~Contributing to Ember.js~
- ~Glossary~

New sections are in bold.

**Comment by locks** [comment]
The following sections are missing from the listing: "The Object Model", "Controllers", "Contributing to Ember.js", "Glossary".

**Comment by MelSumner** [comment]
@locks this was copied and pasted directly from "what does an MVP look like" 

The RFC states these things: 
- the object model section is getting removed
- controllers are going under routing

I think that for now, Glossary and Contributing to Ember should go under References if they need to move at all. I'm not comfortable completely removing them just yet. @jenweber can clarify if she can speak more to her planning intent. 

Does that sound okay?

**Comment by locks** [comment]
We had a call and discussed how to break down the work necessary to complete this task in a way that allows the learning team to continuously release content with minimal impact to the stability of URLs and such.

To that end, the approach is going to roughly be:
1. Re-order and re-title sections. Since this keeps the current URLs, the only impact will be for the "previous"/"next" hyperlinks at the bottom of each page.
2. Add placeholders for the new top-level sections
2.1. Add placeholders for new sub-sections
2.2. Fill out new content
3. Remove content and set up relevant redirects

**Comment by acorncom** [comment]
Looks to have been fixed by #459
