### ISSUE TITLE
Add a Home link above the table of contents

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#437]
Currently the only way to get back to the index of the guides is through the navbar Docs > Guides.
This task is to add a "Home" link between the version selector and the table of contents that links to `https://guides.emberjs.com/release/`.

**Comment by j-brennan** [comment]
I'll take a look at this.

**Comment by j-brennan** [comment]
As the new "Home" link is between the version selector and the TOC, should the link take you to the home of the currently selected version instead of the home of the latest release? So linking to `/v3.8.0` if the user is browsing through the guide for v3.8.0, etc. Apologies if this is what you are implying with `/release/` - but I just wanted to clear that up - as `/release` can bring you to the latest version too.

I also have a question on where to put this home link. What I talk about here does depend on the answer to the above query, so I may be rambling on here for no good reason!

Having looked through some of the code in this area, I see that the TOC for each version also contains an index link. It could be useful here in acting as the "Home" link for each version. However, the current setup does not show this link as `page.skipToc` is set to true. I've attached a screenshot to show what it looks like when displayed. I refer to it as B in the screenshot.

<img width="477" alt="home-link" src="https://user-images.githubusercontent.com/8842238/58369649-2b4c0380-7ef5-11e9-8418-58e638fb1d42.png">

Unfortunately, while it does link to "Home" for that version, it does not quite look right. Some HTML and styling would need to be changed to give us that "Home" link without enclosing it within a section title. And this may upset other areas / projects that use the `table-of-contents` component (of guidemaker-ember-template) with `page.skipToc` set to false.

But I think it is worth pointing out - as it could be that "Home" link we are looking for.. with a little bit of work. Or not, if you just want to link to latest release.

**Comment by locks** [comment]
Closing as stale. Thanks for the discussion everyone!
