### ISSUE TITLE
Migrate testing sections to use qunit-dom?

### ISSUE THREAD

**Issue by rwjblue** [ember-learn/guides-source#562]
[qunit-dom](https://github.com/simplabs/qunit-dom) simplifies making assertions against the DOM, and has been included by default in new ember-cli applications for quite a while (introduced in [this RFC](https://emberjs.github.io/rfcs/0116-qunit-dom.html) and landed in ember-cli back in ember-cli@3.2.0).

An example of the difference between what we have now and what things would look like if we migrated an example from the "Building a simple component" page to qunit-dom is:

```js
  test('should toggle wide class on click', async function(assert) {
    await render(hbs`<RentalListing @rental={{this.rental}} />`);
    assert.notOk(this.element.querySelector('.image.wide'), 'initially rendered small');
    await click('.image');
    assert.ok(this.element.querySelector('.image.wide'), 'rendered wide after click');
    await click('.image');
    assert.notOk(this.element.querySelector('.image.wide'), 'rendered small after second click');
  });
```

to:

```js
  test('should toggle wide class on click', async function(assert) {
    await render(hbs`<RentalListing @rental={{this.rental}} />`);
    assert.dom('.image.wide').doesNotExist('initially rendered small');
    await click('.image');
    assert.dom('.image.wide').exists('rendered wide after click');
    await click('.image');
    assert.dom('.image.wide').doesNotExist('rendered small after second click');
  });
```

## Pages

- [ ] Introduction
- [ ] Test Types
- [ ] Testing Application
- [ ] Testing Basics
- [ ] Testing Components
- [ ] Testing Helpers
- [ ] Testing Controllers
- [ ] Testing Routes
- [ ] Testing Models

**Comment by MonsieurDart** [comment]
We started using the `assert.dom` syntax a few weeks ago and we are very satisfy with it. First it makes the assertion code more readable (imho). But it also makes the assertion message much much clearer, we have the details of the failure (something like « Dom element should exist ») instead of a boolean comparision (something like « Expected true to be false »). 

So I would definitely recommend teaching the « Qunit-dom » technique rather than the « Quint only » path... even though it requires developers to know of an other documentation site (because the `Dom` syntax is not accessible from the plain Qunit documentation).

**Comment by acorncom** [comment]
In addition to making the changes mentioned here, if we make changes to the tutorial we'll want to make sure we update the super rentals example app: https://github.com/ember-learn/super-rentals

**Comment by MonsieurDart** [comment]
Is this issue ready to be implemented or are we waiting for other feedbacks? If ready, I can work on it.

**Comment by acorncom** [comment]
@MonsieurDart please, have at it! 😉

**Comment by locks** [comment]
This has been implemented!
