### ISSUE TITLE
Octane - document fn and on helpers

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#828]
@sivakumar-kailasam is doing this. Thanks Siva!

**Comment by theroncross** [comment]
Hi @sivakumar-kailasam - are you swapping out `{{action}}` usage for `{{on <event> (fn <some-method>)}}`, or just adding documentation? I see that these have been merged in 3.11 so I would think we'd want people to start using them instead of `{{action}}`. I'm happy to file a separate issue and PR if people think it's the right approach and you aren't already doing this.

**Comment by sivakumar-kailasam** [comment]
@theroncross thanks for bringing this up. 

The plan is to do both on the octane guides. Afaik we haven’t discussed porting over these to the main release docs. 

I’ll bring this up in our weekly meeting tomorrow (feel free to join us if you can 🙂). You can follow along by reading the weekly meeting notes as well. 

If you’re looking for other areas to help with then checkout our [octane guides quest issue](https://github.com/ember-learn/guides-source/issues/669https://github.com/ember-learn/guides-source/issues/669) in case any of those interests you.

**Comment by NullVoxPopuli** [comment]
@sivakumar-kailasam are still working on this? is there someway I can help?

**Comment by sivakumar-kailasam** [comment]
Thanks @NullVoxPopuli 🙏

**Comment by NullVoxPopuli** [comment]
Work has begun over here: https://github.com/ember-learn/guides-source/pull/912

**Comment by locks** [comment]
Work finished :)
